### ISSUE TITLE
Configuration page

### ISSUE THREAD

**Issue by psteiwer** [psteiwer/PivotSubscriptions#26]
We need a configuration page to allow users to set up some custom components. Initially, we will need this to be able to properly configure the URL of the unsubscribe link/link to subscription manager. This should include options for:
1. HTTP vs HTTPS
2. Hostname
3. Port
4. Web Application

This should be dynamic enough that we can easily add configuration options in the future. These future enhancements could include Email Styles, Headers, Footers, etc.

**Comment by asinay** [comment]
It would be nice to also let admins customize the "No data for requested pivot" message (and maybe even localize it).

**Comment by hk4** [comment]
Also see commits in hk4/PivotSubscriptions in branch "dev-configuration-page":
- Add check for whether or not the configuration setting for sending an email alert for table error has been set, check configuration setting for default manager email: 209ec65d9e87d4deea806635ecb39375c63a5938
- Build utility class methods for setting configuration globals set in the configuration page: f10d26983dbd4bc4955bdf11eaffff4bdae8dca3
