### ISSUE TITLE
One-time subscription

### ISSUE THREAD

**Issue by asinay** [psteiwer/PivotSubscriptions#70]
I am not sure if this is a good fit for this project, but sometimes, you want to quickly get a pivot table to your inbox, or maybe you want to "job it off" and get it in an email when it is done.

Maybe even delete the pivot table when it is done (since this is a one time analysis).

I currently either make a snapshot of the Pivot and paste it in to an email, or export to Excel and copy it from there, but if it will be part of PivotSubsciption, it will be audited and logged and maybe even cleaned up.

Please let me know what you think.

Thanks,
Asaf

**Comment by psteiwer** [comment]
Assigned to v.15

I see this as allowing an option that says "Run subscription once" with an additional "Send Immediately" option becoming available in addition to the normal scheduling options.

Cleaning up the pivot table after may also be an option, but will need to be considered further
